# Interactive visualisation in Python

## Learning objectives
* Create advanced custom visualisations in Python.
* Create interactive visualisations in a Jupyter notebook.

### Installing relevant packages

In [ ]:
! pip install scipy

In [ ]:
! pip install ipywidgets

In [ ]:
! pip install chart-studio

In [ ]:
! pip install cufflinks

In [ ]:
! pip install pyarrow

### Enable interactive visualisations in Jupyter

In [ ]:
! jupyter nbextension enable --py widgetsnbextension

### Importing required packages

In [4]:
# importing data science helpers
import pandas as pd
import numpy as np
import scipy

# importing the plotly libraries
import chart_studio.plotly as py
import plotly.graph_objs as go
import plotly.express as px

# connecting plotly for offline use
from plotly.offline import iplot, init_notebook_mode
init_notebook_mode(connected=True)

# importing cufflinks libraries
import cufflinks as cf

# connecting cufflinks for offline use
cf.go_offline(connected=True)
cf.set_config_file(colorscale='plotly', world_readable=True)

# extras, for more appealing visuals
from IPython.core.display import HTML
pd.options.display.max_rows = 30
pd.options.display.max_columns = 25

# showing all outputs from code cells
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

## Reading the data

For this project, we'll work with some stats data from `medium.com`.

In [6]:
df = pd.read_parquet('https://github.com/WillKoehrsen/Data-Analysis/blob/master/medium/data/medium_data_2019_01_26?raw=true')
df.head()

,claps,days_since_publication,fans,link,num_responses,publication,published_date,read_ratio,read_time,reads,started_date,tags,text,title,title_word_count,type,views,word_count,claps_per_word,editing_days,<tag>Education,<tag>Data Science,<tag>Towards Data Science,<tag>Machine Learning,<tag>Python
129,2,597.301123,2,https://medium.com/p/screw-the-environment-but...,0,None,2017-06-10 14:25:00+00:00,42.17,7,70,2017-06-10 14:24:00+00:00,"[Climate Change, Economics]","Screw the Environment, but Consider Your Walle...","Screw the Environment, but Consider Your Wallet",8,published,166,1859,0.001076,0,0,0,0,0,0
125,18,589.983168,3,https://medium.com/p/the-vanquishing-of-war-pl...,0,None,2017-06-17 22:02:00+00:00,30.34,14,54,2017-06-17 22:02:00+00:00,"[Climate Change, Humanity, Optimism, History]","The Vanquishing of War, Plague and Famine Part...","The Vanquishing of War, Plague and Famine",8,published,178,3891,0.004626,0,0,0,0,0,0
132,51,577.363292,20,https://medium.com/p/capstone-project-mercedes...,0,None,2017-06-30 12:55:00+00:00,20.02,42,222,2017-06-30 12:00:00+00:00,"[Machine Learning, Python, Udacity, Kaggle]",Capstone Project: Mercedes-Benz Greener Manufa...,Capstone Project: Mercedes-Benz Greener Manufa...,7,published,1109,12025,0.004241,0,0,0,0,1,1
126,0,576.520688,0,https://medium.com/p/home-of-the-scared-5af0fe...,0,None,2017-07-01 09:08:00+00:00,35.85,9,19,2017-06-30 18:21:00+00:00,"[Politics, Books, News, Media Criticism]",Home of the Scared A review of A Culture of Fe...,Home of the Scared,4,published,53,2533,0.000000,0,0,0,0,0,0
121,0,572.533035,0,https://medium.com/p/the-triumph-of-peace-f485...,0,None,2017-07-05 08:51:00+00:00,8.47,14,5,2017-07-03 20:18:00+00:00,"[Books, Psychology, History, Humanism]",The Triumph of Peace A review of The Better An...,The Triumph of Peace,4,published,59,3892,0.000000,1,0,0,0,0,0

### Looking at the descriptive details of the data

In [7]:
df.describe()

,claps,days_since_publication,fans,num_responses,read_ratio,read_time,reads,title_word_count,views,word_count,claps_per_word,editing_days,<tag>Education,<tag>Data Science,<tag>Towards Data Science,<tag>Machine Learning,<tag>Python
count,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000
mean,1815.263158,248.407273,352.052632,7.045113,29.074662,12.917293,6336.300752,7.127820,23404.030075,3029.120301,0.957638,20.330827,0.729323,0.609023,0.436090,0.383459,0.315789
std,2449.074661,179.370879,479.060117,9.056108,12.417670,9.510795,9007.284726,3.158475,33995.636496,2393.414456,1.846756,74.111579,0.445989,0.489814,0.497774,0.488067,0.466587
min,0.000000,1.218629,0.000000,0.000000,8.110000,1.000000,1.000000,2.000000,3.000000,163.000000,0.000000,-13.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,121.000000,74.543822,23.000000,0.000000,20.020000,8.000000,363.000000,5.000000,1375.000000,1653.000000,0.052115,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,815.000000,245.416130,136.000000,4.000000,27.060000,10.000000,2049.000000,7.000000,7608.000000,2456.000000,0.421525,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
75%,2700.000000,376.080598,528.000000,12.000000,34.910000,14.000000,7815.000000,8.000000,30141.000000,3553.000000,1.099366,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,13600.000000,597.301123,2588.000000,59.000000,74.370000,54.000000,41978.000000,16.000000,173714.000000,15063.000000,17.891817,349.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [8]:
from ipywidgets import interact, interact_manual, widgets

###  Exercise 1

Create an interactive function called `show_articles_more_than`, that filters a dataset based on a selected column and a threshold value.

It should allow the user to:
* input a column name using a textbox
* choose a numeric threshold using a slider
* It should display a formatted heading showing the filter condition
* It should return a table of articles where the selected column value is greater than the chosen threshold
* The output should include the floowing columns title, claps, published_date, read_time, tags, views, and reads.

In [9]:
@interact
def show_articles_more_than(column='claps', x=5000):
    display(HTML(f'<h3> Showing articles with more than {x} {column} <h3>'))
    display(df.loc[df[column] > x, ['title', 'claps', 'published_date', 'read_time', 'tags', 'views', 'reads']])

interactive(children=(Text(value='claps', description='column'), IntSlider(value=5000, description='x', max=15…

### Exercise 2

Create an interactive function called `show_titles_more_than`, that filters a dataset based on a selected column and a value.

It should allow the user to:
* select a column name from a dropdown menu with options: read_time, views, and reads
* select a number from a dropdown, that corresponds to the column name with options: greater than 10, greater than 50000, and greater than 10
* It should display a formatted heading showing the filter condition
* It should return a table of articles where the selected column value is greater than the chosen threshold
* The output should include the following columns: title, published_date, read_time, tags, views, and reads.

In [10]:
@interact
def show_titles_more_than(columns=['read_time', 'views', 'reads'],
                          x= [10, 50000, 10]):
    display(HTML(f'<h3> Showing articles with more than {x} {columns}<h3>'))
    display(df.loc[df[columns] > x, ['title', 'claps', 'published_date', 'read_time', 'tags', 'views', 'reads']])

interactive(children=(Dropdown(description='columns', options=('read_time', 'views', 'reads'), value='read_tim…

### Exercise 3

Create an interactive function called `correlations` that computes and displays the correlation between two columns in a dataset.

It should allow the user to:
* select a first numeric column from a dropdown.
* select a second numeric column from a dropdown.
* It should print the correlation value between the two selected columns in a formatted string.

In [11]:
@interact
def correlations(column_1= list(df.select_dtypes('number').columns),
                 column_2= list(df.select_dtypes('number').columns)
                 ):
    
    if column_1 == column_2:
        print(f'Both columns should be different')
    else:
        print(f"Correlation value: {df[column_1].corr(df[column_2])}")

interactive(children=(Dropdown(description='column_1', options=('claps', 'days_since_publication', 'fans', 'nu…

### Exercise 4

Create an interactive function called `scatter_plot` that generates a scatter plot between two numeric columns in a dataset using plotly.

It should allow the user to:
* select an x-axis column from a dropdown of numeric columns in the dataframe.
* select a y-axis column from a dropdown numeric columns, but defaulting to the second column in the list
* Generate a scatter plot

In [12]:
@interact
def scatter_plot(x= list(df.select_dtypes('number').columns),
                y= list(df.select_dtypes('number').columns)[1:]):
    
    if x == y:
        print(f"Both columns should not be the same.")
    else:
        figure = px.scatter(df, x=x, y=y, title=f"{y.title()} vs {x.title()}")
        figure.show()

interactive(children=(Dropdown(description='x', options=('claps', 'days_since_publication', 'fans', 'num_respo…

### Exercise 5

Create an interactive function called `plot_corrs` that generates a customisable annotated correlation heatmap using plotly.figure_factory.

It should:
* Define a list of colorscales called `cscales` containing the following options: `'Greys'`, `'YlGnBu'`, `'Greens'`, `'YlOrRd'`, `'Bluered'`, `'RdBu'`, `'Reds'`, `'Blues'`, `'Picnic'`, '`Rainbow'`, `'Portland'`, `'Jet'`, `'Hot'`, `'Blackbody'`, `'Earth'`, `'Electric'`, `'Viridis'`, `'Cividis'`
* Allow the user to select a colorscale from a dropdown populated with cscales
* Generate an annotated heatmap with correlation values rounded to 2 decimal places

In [ ]:
cscales = ['Greys', 'YlGnBu', 'Greens', 'YlOrRd', 'Bluered', 'RdBu', 
           'Reds', 'Blues', 'Picnic', 'Rainbow', 'Portland', 'Jet', 
           'Hot', 'Blackbody', 'Earth', 'Electric', 'Viridis', 'Cividis']

import plotly.figure_factory as ff

corrs = df.corr(numeric_only=True)

@interact
def plot_heatmap(colourscale=cscales):
    figure = ff.create_annotated_heatmap(z= corrs.round(2).values,
                                         x = list(corrs.columns),
                                         y = list(corrs.index),
                                         colorscale=colourscale,
                                         annotation_text= corrs.round(2).values)
    
    figure.show()

interactive(children=(Dropdown(description='colourscale', options=('Greys', 'YlGnBu', 'Greens', 'YlOrRd', 'Blu…